### ISSUE TITLE
Errors in log Domoticz

### ISSUE THREAD

**Issue by poudenes** [dnpwwo/Domoticz-Kodi-Plugin#5]
Domoticz Version: 4.9960
Build Hash: 3974b5c4
Compile Date: 2018-08-29 11:43:56
dzVents Version: 2.4.7
Python Version: 3.6.4
GCC 6.3.0 20170516

Got this error in logs Kodi Plugin version: 

```
2018-08-29 14:40:49.916  (Kodi) Unhandled exception in onHeartbeat, forcing disconnect.
2018-08-29 14:40:49.916  (Kodi) Device has disconnected
```

Did a update and manual select NONE at debug selection. Because this was empty.
After update the error is gone. Maybe a bug in script that is select always NONE if it is not change?

**Comment by dnpwwo** [comment]
As far as I can see the debug level is referenced in onHeartbeat so that is strange.

Glad you worked it out, I will look at adding a check in the next version.
